-- Script generated by Redgate Compare v1.37.1.951


-- deployment: Creating customers_customer_feedback.ClientID...
ALTER TABLE customers_customer_feedback ADD COLUMN ClientID int NULL;


-- deployment: Dropping customers_customer.SocialSecurity...
ALTER TABLE customers_customer DROP COLUMN SocialSecurity;

