-- Script generated by Redgate Compare v1.37.1.951


-- deployment: Dropping customers_customer.ClientID...
ALTER TABLE customers_customer DROP COLUMN ClientID;


-- deployment: Creating customers_customer.socialmedia...
ALTER TABLE customers_customer ADD COLUMN socialmedia varchar(100) NULL;

