-- Script generated by Redgate Compare v1.37.1.951


-- deployment: Dropping customers_customer_feedback.ClientID...
ALTER TABLE customers_customer_feedback DROP COLUMN ClientID;


-- deployment: Creating customers_customer.SocialSecurity...
ALTER TABLE customers_customer ADD COLUMN SocialSecurity varchar(100) NULL;

